In [1]:
# numpy
# 多次元配列を効率的に扱うライブラリ
import numpy as np

In [ ]:
# np.array()    配列の構築
# リストからの配列作成
a = np.array([1, 2, 3])
print(a)    # [1 2 3]
# タプルからの配列作成
b = np.array((1, 2, 3))
print(b)

a   # array([1, 2, 3])となり全くの別物であることがわかる

[1 2 3]
[1 2 3]


array([1, 2, 3])

In [5]:
# 型名                説明

# numpy.int32         整数（32-bit）を表す型

# numpy.float64       実数（64-bit）を表す型

# numpy.complex128    複素数（64-bit実数の組）を表す型

# numpy.bool_         真理値を表す型

print(np.array([-1, 0, 1], dtype = np.int32))
print(np.array([-1, 0, 1], dtype = np.float64))
print(np.array([-1, 0, 1], dtype = np.complex128))
print(np.array([-1, 0, 1], dtype = np.bool_))

[-1  0  1]
[-1.  0.  1.]
[-1.+0.j  0.+0.j  1.+0.j]
[ True False  True]


In [ ]:
# 多次元配列
print(np.array([[2,3], [4,5]]))
print("")
print(np.array([[1,2], [3,4]]+[[5,6], [7,8]]))
# 長さが異なるとエラーになる

[[2 3]
 [4 5]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [52]:
import numpy as np
a1 = np.array([0, 1, 2, 3, 4, 5])
a2 = a1.reshape(2,3)    # (2,3)行列
print("\n(1)-1 reshape()")
print(a2)

a1[1] = 6
# a1 a2 は内部的にデータを共有している
print("\n(1)-2")
print(a1)
print(a2)

# ravel()-------------------------------------------------------
# 多次元配列を1次元に戻せる
a = np.array([0,1,2,3,4,5]).reshape(2,3)
print("\n(2)-1 ravel()")
print(a.ravel())

elems = np.array([0,1,2,3,4,5])
a = elems.reshape(2,3).ravel()
elems[1] = 6
print("(2)-2")
print(a)


(1)-1 reshape()
[[0 1 2]
 [3 4 5]]

(1)-2
[0 6 2 3 4 5]
[[0 6 2]
 [3 4 5]]

(2)-1 ravel()
[0 1 2 3 4 5]
(2)-2
[0 6 2 3 4 5]


In [ ]:
print(a.reshape(2,3))
print("")
print(a.dtype,"： aの要素型")
print(a.shape,"： aの形(長さ)")
print(a.ndim,"： aの次元数")
print(a.size,"： aの要素数")
print(a.flat,"： aの1次元表現")
print(a.T,"： aの転置")

[[0 6 2]
 [3 4 5]]

int64 ： aの要素型
(6,) ： aの形
1 ： aの次元数
6 ： aの要素数
<numpy.flatiter object at 0x000001CEA3BD63C0> ： aの1次元表現
[0 6 2 3 4 5] ： aの転置


In [ ]:
# arange(), linspace(), zeros, ones

# arange関数--------------------------------------------------------
# array rangeの略
# 開始値、終了値、刻み幅を指定して配列を生成　リストの扱いと同じかんじ
print("(1) arange関数")
print(np.arange(3))
print(np.arange(0, 1, 0.2))

# linspace関数---------------------------------------------------------
# 範囲を等分割した配列を生成
print("\n(2) linspace関数")
print(np.linspace(0,10,5))

# zeros と ones-------------------------------------------------------
# zeros : 0からなる配列を生成
# ones : 1からなる配列を生成
print("\n(3) zerosとones")
print("zeros")
print(np.zeros(4))
print(np.zeros((2,3)))
print("ones")
print(np.ones(4))
print(np.ones((2,3)))

(1) arange関数
[0 1 2]
[0.  0.2 0.4 0.6 0.8]

(2) linspace関数
[ 0.   2.5  5.   7.5 10. ]

(3) zerosとones
zeros
[0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
ones
[1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [49]:
# random.rand関数-------------------------------------------------
# 0<= x < 1 未満の乱数から生成
print("(1) random.rand")
print(np.random.rand(4))
print("\n",np.random.rand(2,3))

(1) random.rand
[0.34353136 0.92174666 0.76917779 0.79345177]

 [[0.16898503 0.34335622 0.9395477 ]
 [0.9944857  0.2864689  0.11013534]]


In [ ]:
# 練習問題-----------------------------------------------------------------
print("\n練習問題")
def arange_square_matrix(n):
    result = []
    for i in range(n):
        a = np.arange(i, i+n)
        result.append(a)
    # print(result)　
    #[array([0, 1, 2]), array([1, 2, 3]), array([2, 3, 4])]
    # ただのリスト状態
    return np.array(result) #array()配列化

# 模範解答 -----------------------------------------------------------
def arange_square_matrix_T(n):
    return np.arange(n) + np.arange(n)[:,None]
# np.arange -> n行と指定した
# [:,None] (.reshape(-1,1)も同様) 
#    ➥ n行のものを縦1列にする
# つまり。。。（ｎ, １）＋（１, ｎ）＝（ｎ, ｎ）ということ！！

print(arange_square_matrix(3))
print(all(map(all,(arange_square_matrix_T(3) == np.array([[0,1,2],[1,2,3],[2,3,4]])))))


練習問題
[[0 1 2]
 [1 2 3]
 [2 3 4]]
True


In [78]:
# 配列要素の操作

# インデックスアクセス
print("インデックスアクセス")
a = np.arange(3)
print(a)
print(a[1])
a[-1] = 3
print(a)

a = np.arange(6).reshape(2,3)
print(a)

# 行、列をまとめて指定
# print(a[1,2])   # 5
a[1,2] = 6
print(a)

# スライス
print("\nスライス")
a = np.arange(5)    # [0 1 2 3 4]
print(a[1:4])   # [1 2 3]
print(a[1:])    # [1 2 3 4]
print(a[:-2])   # [0 1 2]
print(a[::2])   # [0 2 4]
print(a[::-1])  # [4 3 2 1 0]

インデックスアクセス
[0 1 2]
1
[0 1 3]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 6]]

スライス
[1 2 3]
[1 2 3 4]
[0 1 2]
[0 2 4]
[4 3 2 1 0]


In [84]:
a = np.arange(5)
print(a)    # [0 1 2 3 4]
a[1:4] = 6
print(a)    # [0 6 6 6 4]
a = np.arange(5)
a[::2] = 6
print(a)    # [6 1 6 3 6]

# リストでは不可
a = [0, 1, 2, 3, 4]
a[1:4] = [6]    # [0, 6, 4]

a = np.arange(9).reshape(3,3)
# [[0 1 2]
#  [3 4 5]
#  [6 7 8]]

print(a[:2, :2])
# [[0 1]
#  [3 4]]

print(a[1:,1:])
# [[4 5]
#  [7 8]]

[0 1 2 3 4]
[0 6 6 6 4]
[6 1 6 3 6]
[[0 1]
 [3 4]]
[[4 5]
 [7 8]]


In [ ]:
# for文------------------------------------------------------------
print("(1)")
for v in np.arange(3):
    print(v)
    # 0 1 2縦書き

print("\n(2)")
for row in np.arange(6).reshape(2,3):
    print(row)
    # [0 1 2]
    # [3 4 5]

print("\n(3)")
# np.ndenumerate() ----------------------------------------------------
# 多次元配列版のenumerate関数（番号の割り振り）
for idx, e in np.ndenumerate(np.arange(6).reshape(2,3)):
    print(idx, e)
    # (0, 0) 0
    # (0, 1) 1
    # (0, 2) 2 ....

print("\n(4)")
for idx, e in np.ndenumerate(np.arange(3)):
    print(idx, e)

# arange()は生み出す、array()は既存のものを配列にする！！

(1)
0
1
2

(2)
[0 1 2]
[3 4 5]

(3)
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5

(4)
(0,) 0
(1,) 1
(2,) 2


In [8]:
# 配列のスカラ演算　＊＊ 超大事！！！＊＊
a = np.arange(4)    # [0 1 2 3]

print(a + 1) # 各要素に１を加算
print(a ** 2) # 各要素を2乗

b = a+1 # [1 2 3 4]
print(1 / b) # [1. 0.5 0.333 0.25]
print( 9 // b) # [9 4 3 2]

print("\n配列同士の計算")
# 線形での計算とは別
a = np.arange(4).reshape(2,2) # [[0 1] [2 3]]
b = np.arange(1,5).reshape(2,2) # [[1 2] [3 4]]

print(a + b) # [[1 3] [5 7]]
print(a * b) # [[0 2] [6 12]]
print(a / b) # [0 0.5] [0.666 0.75]]

print("")
c = 3 * a # [[0 3] [6 9]]
print(c // b) # [[0 1] [ 2 2]]
print(a ** b) # [[0 1] [8 81]]

[1 2 3 4]
[0 1 4 9]
[1.         0.5        0.33333333 0.25      ]
[9 4 3 2]

配列同士の計算
[[1 3]
 [5 7]]
[[ 0  2]
 [ 6 12]]
[[0.         0.5       ]
 [0.66666667 0.75      ]]

[[0 1]
 [2 2]]
[[ 0  1]
 [ 8 81]]


In [ ]:
# ユニバーサル関数
# sqrt,log などの特定の演算を与えた値を返す関数のこと
a = np.zeros(3) + 2 # [2. 2. 2.]
print(np.sqrt(a)) # [1.41421356  1.41421356  1.41421356]
b = np.zeros((2,2)) + 2 # [[2 2] [2 2]]
print(np.sqrt(2)) # [1.41421356]  0次元配列を扱うことも可能

[1.41421356 1.41421356 1.41421356]
1.4142135623730951


In [ ]:
# dot()  線形での積と同様！！！！
print("dot関数")
np.dot(np.arange(4), np.arange(1,5))
print(np.dot(np.arange(4).reshape(2,2), np.arange(1,5).reshape(2,2)))
# [[0 1]  *  [[1 2]   =  [[3  4]]
#  [2 3]]     [3 4]]      [11 16]

# sort()
print("\nsort関数")
a = np.array([3, 4, -1, 0, 2])
a.sort() # インプレースなのでsort()事態はNoneを返す＝print(a.sort())はだめ
print(a) # [-1, 0, 2, 3, 4]

# sum, max, min, mean 関数
print("\nsum, max, min, mean 関数")
a = np.arange(6).reshape(2,3) # [[0 1 2] [3 4 5]]
print(a.sum()) # 15
print(a.sum(0)) # [3 5 7]

dot関数
[[ 3  4]
 [11 16]]

sort関数
[-1  0  2  3  4]

sum, max, min, mean 関数
15
[3 5 7]


In [ ]:
# 配列の保存と復元　savetxt(), loadtxt()

# savetxt() -------------------------------------------------------
# ファイル名を付けテキストで保存
np.savetxt("arange3.txt", np.arange(3))
np.savetxt("arange2x3.txt", np.arange(6).reshape(2,3))

# loadtxt() ----------------------------------------------------------
# ファイルを出力する
a = np.loadtxt("arange2x3.txt")
print(a)
print("")
print(np.loadtxt("arange3.txt"))

# .txtと.gz -------------------------------------------------------
# .gzにするとzipファイルとして保存、または解凍して復元する

[[0. 1. 2.]
 [3. 4. 5.]]

[0. 1. 2.]


In [ ]:
# 真理値配列
# 条件を付けることでTrue、Falseで返す
# インデックス指定をすることで特定のインデックスを返してくれる
a = np.arange(6).reshape(2,3)
print("True Falseで返す")
print(a) # [[0 1 2] [3 4 5]]
print(a < 3) # [[True True True] [False False False]]

print("\nインデックスとして利用")
a = np.array([0, 1, 2, -3, -4, 5, -6, -7])
print(a[a < 0]) # [-3 -4 -6 -7]
print(a[(a < 0) & (a % 2 == 0)]) # [-4 -6]
a[a<0] = 5 # [0 1 2 5 5 5 5]
print(a)

True Falseで返す
[[0 1 2]
 [3 4 5]]
[[ True  True  True]
 [False False False]]

インデックスとして利用
[-3 -4 -6 -7]
[-4 -6]
[0 1 2 5 5 5 5 5]


In [22]:
# 線形代数の演算 matmul() ---------------------------------------------------
# matmul() -> 行列積専用の関数 .dot()と近縁
# .identity() 単位行列を作れちゃうよ
I = np.identity(3)
print(I) # [[1 0 0] [0 1 0] [0 0 1]]
a = np.arange(9).reshape(3,3) # [[0 1 2] [3 4 5] [6 7 8]]
print(np.matmul(a, I)) # [[0 1 2] [3 4 5] [6 7 8]]

# .linalg.norm() -> ノルム(ベクトルの長さ、大きさ)を求める
# 例：(0,0)から(3,4)までのノルム
# √(3**2 + 4**2) = √25 = 5
print("\nノルムを求める")
print(str(np.ones(3)) + "のノルム")
print(np.linalg.norm(np.ones(3)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

ノルムを求める
[1. 1. 1.]のノルム
1.7320508075688772
